# DO NOT EDIT! This file is generated by ./update.sh
{
  lib,
  runCommand,
  nixosOptionsDoc,
  pkgs,
  ...
}: let
  inherit (lib) hasPrefix removePrefix;
  # evaluate our options
  eval = lib.evalModules {
    # The populated modules array
    modules = [
      ../modules/security/options.nix
      ../modules/containers/options.nix
      ../modules/browser/options.nix
      ../modules/services/options.nix
      ../modules/virtualisation/options.nix
      ../modules/gaming/options.nix
      ../modules/network/options.nix
      ../modules/dev/options.nix
      ../modules/display-manager/options.nix
      ../modules/terminal/options.nix
      ../modules/media/options.nix
      ../modules/editor/options.nix
      ../modules/social/options.nix
      ../modules/desktop/options.nix
      ../modules/graphics/options.nix
    ];
  };

  # generate our docs
  optionsDoc = nixosOptionsDoc {
    options = eval.options.modules;
    transformOptions = opt:
      opt
      // {
        declarations =
          map
          (decl:
            if hasPrefix (toString ../..) (toString decl)
            then let
              subpath = removePrefix "/" (removePrefix (toString ../.) (toString decl));
            in {
              url = "https://github.com/jamesatintegratnio/nix-dots/blob/main/${subpath}";
              name = subpath;
            }
            else decl)
          opt.declarations;
      };
    documentType = "none";
  };
in
  runCommand "index.md" {} ''
    cat ${optionsDoc.optionsCommonMark} >> $out
  ''
