# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  inputs,
  pkgs,
  modulesPath,
  ...
}:
with lib; {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  config = mkMerge [
    (mkIf (config.services.qemuGuest.enable == false) {
      fileSystems."/" = {
        device = "/dev/disk/by-label/NIXROOT";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-label/NIXBOOT";
        fsType = "vfat";
      };

      swapDevices = [
        {
          device = "/.swapfile";
        }
      ];
    })
    {
      boot = {
        kernelPackages = pkgs.linuxPackages_6_6;
        kernelModules = ["kvm-intel"];
        initrd = {
          availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
          kernelModules = [];
        };
        extraModulePackages = [];
        # Bootloader.
        loader = {
          systemd-boot.enable = true;
          efi = {
            canTouchEfiVariables = true;
            efiSysMountPoint = "/boot";
          };
        };
        # Enable building for ARM
        binfmt.emulatedSystems = ["aarch64-linux"];
        # Setup keyfile
        # initrd.secrets = {
        #   "/crypto_keyfile.bin" = null;
        # };
        extraModprobeConfig = ''options bluetooth disable_ertm=1 snd slots=snd-hda-intel'';
      };

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    }
  ];
}
