name: "Build"
on:
  pull_request:
    paths:
      - "**/*.nix"
  push:
    branches:
      - main
    paths:
      - "**/*.nix"
jobs:
  tests:
    name: Check that flake builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
