on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Nix Targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Build lappy package
        run: nix build .#nixosConfigurations.lappy.config.system.build.toplevel